name: "vremenska-kteh"
services:
  prod:
    container_name: prod-container
    restart: always
    build:
      context: .
      dockerfile: Prod.Dockerfile
    ports:
      - "3000:3000"
    env_file: ".env.local"
    volumes:
      - modules:/app/node_modules/
    networks:
      - web
    healthcheck:
      test: node scripts/health-check.mjs
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 5s
  dev:
    container_name: dev-container
    restart: always
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - "5173:3000"
    env_file: ".env.local"
    volumes:
      - .:/app
      - modules-dev:/app/node_modules/
    networks:
      - web
    profiles:
      - dev
volumes:
  modules:
  modules-dev:
networks:
  web:
    driver: bridge
